package ba.unsa.etf.rpr.Business;

import ba.unsa.etf.rpr.Exceptions.GameException;
import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Game;
import ba.unsa.etf.rpr.domain.Genre;
import javafx.scene.control.Alert;

import java.util.List;

/**
 * The type Game manager.
 */
public class GameManager {

    /**
     * Add game.
     *
     * @param game the game
     * @return the game
     * @throws GameException the game exception
     */
    public Game add(Game game) throws GameException {
        if(game.getId() != 0) throw new GameException("Id must be 0, because it's autogenerated");
        return DaoFactory.gameDao().add(game);
    }


    /**
     * Validate game.
     *
     * @param game the game
     * @throws GameException the game exception
     */
    public void validateGame(Game game) throws GameException{
        if(game.getGameTitle() == null || game.getGameTitle().length() <= 3 )
            throw new GameException("Game title must be longer than 3 letters");
        else if(game.getRequiredRAM() == 0 ||game.getRequiredMemory() == 0 ||game.getRequiredGPU().equals("") ||game.getRequiredCPU().equals(""))
            throw new GameException("The specifications are incorrect");
    }

    /**
     * Update.
     *
     * @param game the game
     * @throws GameException the game exception
     */
    public void update(Game game) throws GameException {
        DaoFactory.gameDao().update(game);
    }

    /**
     * Delete.
     *
     * @param id the id
     * @throws GameException the game exception
     */
    public void delete(int id) throws GameException {
        DaoFactory.gameDao().delete(id);
    }

    /**
     * Gets all.
     *
     * @return the all
     * @throws GameException the game exception
     */
    public List<Game> getAll() throws GameException {
        return DaoFactory.gameDao().getAll();
    }

    /**
     * Search by genres list.
     *
     * @param genre the genre
     * @return the list
     */
    public List<Game> searchByGenres(Genre genre) {
        try {
            List<Game> games = DaoFactory.gameDao().searchByGenreName(genre);
            return games;
        } catch (GameException g) {
            Alert alert = new Alert(Alert.AlertType.WARNING);
            alert.setTitle("You can't add games to databse");
            alert.setHeaderText("Database error occured");
            alert.setContentText(g.getMessage());
            alert.showAndWait();
        }
        return null;
    }
}

